// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Address controller
* Do not edit this file manually
*/
import {HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';
import {inject, Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT} from '../tokens';
import {AddressResponse, CreateAddressRequest, RequestOptions, UpdateAddressRequest} from '../models';

@Injectable({ providedIn: "root" })
export class AddressService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiAddressGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AddressResponse>>;
    apiAddressGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AddressResponse>>>;
    apiAddressGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AddressResponse>>>;
    apiAddressGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressCreatePost(createAddressRequest: CreateAddressRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressCreatePost(createAddressRequest: CreateAddressRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressCreatePost(createAddressRequest: CreateAddressRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressCreatePost(createAddressRequest: CreateAddressRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/Create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressUpdatePut(updateAddressRequest: UpdateAddressRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressUpdatePut(updateAddressRequest: UpdateAddressRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressUpdatePut(updateAddressRequest: UpdateAddressRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressUpdatePut(updateAddressRequest: UpdateAddressRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/Update`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiAddressIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiAddressIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiAddressIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressGetAllByUserIdByAdminUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AddressResponse>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AddressResponse>>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AddressResponse>>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/GetAllByUserIdByAdmin/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressCreateByAdminPost(createAddressRequest: CreateAddressRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressCreateByAdminPost(createAddressRequest: CreateAddressRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressCreateByAdminPost(createAddressRequest: CreateAddressRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressCreateByAdminPost(createAddressRequest: CreateAddressRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/CreateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressUpdateByAdminPut(updateAddressRequest: UpdateAddressRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressUpdateByAdminPut(updateAddressRequest: UpdateAddressRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressUpdateByAdminPut(updateAddressRequest: UpdateAddressRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressUpdateByAdminPut(updateAddressRequest: UpdateAddressRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address/UpdateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
