// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Address controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AddressResponse, ApiAddressCreatePostParams, ApiAddressUpdatePutParams, ApiAddressIdDeleteParams, ApiAddressGetAllByUserIdByAdminUserIdGetParams, ApiAddressCreateByAdminPostParams, ApiAddressUpdateByAdminPutParams } from "../models";

@Service()
export class ApiAddressService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiAddressGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AddressResponse>>;
    apiAddressGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AddressResponse>>>;
    apiAddressGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AddressResponse>>>;
    apiAddressGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Address`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressCreatePost(request: ApiAddressCreatePostParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressCreatePost(request: ApiAddressCreatePostParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressCreatePost(request: ApiAddressCreatePostParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressCreatePost(request: ApiAddressCreatePostParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { createAddressRequest } = request;
        const url = `${this.basePath}/api/Address/Create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressUpdatePut(request: ApiAddressUpdatePutParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressUpdatePut(request: ApiAddressUpdatePutParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressUpdatePut(request: ApiAddressUpdatePutParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressUpdatePut(request: ApiAddressUpdatePutParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { updateAddressRequest } = request;
        const url = `${this.basePath}/api/Address/Update`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressIdDelete(request: ApiAddressIdDeleteParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiAddressIdDelete(request: ApiAddressIdDeleteParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiAddressIdDelete(request: ApiAddressIdDeleteParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiAddressIdDelete(request: ApiAddressIdDeleteParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { id } = request;
        const url = `${this.basePath}/api/Address/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressGetAllByUserIdByAdminUserIdGet(request: ApiAddressGetAllByUserIdByAdminUserIdGetParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AddressResponse>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(request: ApiAddressGetAllByUserIdByAdminUserIdGetParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AddressResponse>>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(request: ApiAddressGetAllByUserIdByAdminUserIdGetParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AddressResponse>>>;
    apiAddressGetAllByUserIdByAdminUserIdGet(request: ApiAddressGetAllByUserIdByAdminUserIdGetParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { userId } = request;
        const url = `${this.basePath}/api/Address/GetAllByUserIdByAdmin/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressCreateByAdminPost(request: ApiAddressCreateByAdminPostParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressCreateByAdminPost(request: ApiAddressCreateByAdminPostParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressCreateByAdminPost(request: ApiAddressCreateByAdminPostParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressCreateByAdminPost(request: ApiAddressCreateByAdminPostParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { createAddressRequest } = request;
        const url = `${this.basePath}/api/Address/CreateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAddressUpdateByAdminPut(request: ApiAddressUpdateByAdminPutParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponse>;
    apiAddressUpdateByAdminPut(request: ApiAddressUpdateByAdminPutParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponse>>;
    apiAddressUpdateByAdminPut(request: ApiAddressUpdateByAdminPutParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponse>>;
    apiAddressUpdateByAdminPut(request: ApiAddressUpdateByAdminPutParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { updateAddressRequest } = request;
        const url = `${this.basePath}/api/Address/UpdateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateAddressRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
