// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Auth controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { ApiAuthLoginPostParams, RequestOptions, UserResponse, ApiAuthRegisterPostParams, RegisterResponse } from "../models";

@Service()
export class ApiAuthService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiAuthLoginPost(request: ApiAuthLoginPostParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiAuthLoginPost(request: ApiAuthLoginPostParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiAuthLoginPost(request: ApiAuthLoginPostParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiAuthLoginPost(request: ApiAuthLoginPostParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { loginRequest } = request;
        const url = `${this.basePath}/api/Auth/Login`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: loginRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiAuthRegisterPost(request: ApiAuthRegisterPostParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<RegisterResponse>;
    apiAuthRegisterPost(request: ApiAuthRegisterPostParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RegisterResponse>>;
    apiAuthRegisterPost(request: ApiAuthRegisterPostParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RegisterResponse>>;
    apiAuthRegisterPost(request: ApiAuthRegisterPostParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { registerRequest } = request;
        const url = `${this.basePath}/api/Auth/Register`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: registerRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
