// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Cart controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CartResponse, AddCartItemRequest, UpdateCartItemRequest } from "../models";

@Injectable({ providedIn: "root" })
export class CartService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiCartGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<CartResponse>;
    apiCartGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartResponse>>;
    apiCartGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartResponse>>;
    apiCartGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Cart`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCartAddItemPost(addCartItemRequest: AddCartItemRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartResponse>;
    apiCartAddItemPost(addCartItemRequest: AddCartItemRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartResponse>>;
    apiCartAddItemPost(addCartItemRequest: AddCartItemRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartResponse>>;
    apiCartAddItemPost(addCartItemRequest: AddCartItemRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Cart/AddItem`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: addCartItemRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCartUpdateItemPut(updateCartItemRequest: UpdateCartItemRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartResponse>;
    apiCartUpdateItemPut(updateCartItemRequest: UpdateCartItemRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartResponse>>;
    apiCartUpdateItemPut(updateCartItemRequest: UpdateCartItemRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartResponse>>;
    apiCartUpdateItemPut(updateCartItemRequest: UpdateCartItemRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Cart/UpdateItem`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateCartItemRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCartRemoveItemProductIdDelete(productId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartResponse>;
    apiCartRemoveItemProductIdDelete(productId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartResponse>>;
    apiCartRemoveItemProductIdDelete(productId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartResponse>>;
    apiCartRemoveItemProductIdDelete(productId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Cart/RemoveItem/${productId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCartClearDelete(observe?: 'body', options?: RequestOptions<'json'>): Observable<CartResponse>;
    apiCartClearDelete(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartResponse>>;
    apiCartClearDelete(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartResponse>>;
    apiCartClearDelete(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Cart/Clear`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
