// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Category controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CategoryResponse, ApiCategoryCreateByAdminPostParams, ApiCategoryUpdateByAdminPutParams, ApiCategoryDeleteByAdminIdDeleteParams } from "../models";

@Service()
export class ApiCategoryService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiCategoryGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CategoryResponse>>;
    apiCategoryGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CategoryResponse>>>;
    apiCategoryGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CategoryResponse>>>;
    apiCategoryGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Category`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCategoryCreateByAdminPost(request: ApiCategoryCreateByAdminPostParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryResponse>;
    apiCategoryCreateByAdminPost(request: ApiCategoryCreateByAdminPostParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryResponse>>;
    apiCategoryCreateByAdminPost(request: ApiCategoryCreateByAdminPostParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryResponse>>;
    apiCategoryCreateByAdminPost(request: ApiCategoryCreateByAdminPostParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { createCategoryRequest } = request;
        const url = `${this.basePath}/api/Category/CreateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createCategoryRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCategoryUpdateByAdminPut(request: ApiCategoryUpdateByAdminPutParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryResponse>;
    apiCategoryUpdateByAdminPut(request: ApiCategoryUpdateByAdminPutParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryResponse>>;
    apiCategoryUpdateByAdminPut(request: ApiCategoryUpdateByAdminPutParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryResponse>>;
    apiCategoryUpdateByAdminPut(request: ApiCategoryUpdateByAdminPutParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { updateCategoryRequest } = request;
        const url = `${this.basePath}/api/Category/UpdateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateCategoryRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiCategoryDeleteByAdminIdDelete(request: ApiCategoryDeleteByAdminIdDeleteParams, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiCategoryDeleteByAdminIdDelete(request: ApiCategoryDeleteByAdminIdDeleteParams, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiCategoryDeleteByAdminIdDelete(request: ApiCategoryDeleteByAdminIdDeleteParams, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiCategoryDeleteByAdminIdDelete(request: ApiCategoryDeleteByAdminIdDeleteParams, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const { id } = request;
        const url = `${this.basePath}/api/Category/DeleteByAdmin/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
