// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Order controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateOrderRequest, RequestOptions, OrderDetailResponse, OrderResponse, OrderStatus, PagedResultOfOrderResponse, UpdateOrderStatusRequest } from "../models";

@Injectable({ providedIn: "root" })
export class OrderService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiOrderCreatePost(createOrderRequest: CreateOrderRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrderDetailResponse>;
    apiOrderCreatePost(createOrderRequest: CreateOrderRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrderDetailResponse>>;
    apiOrderCreatePost(createOrderRequest: CreateOrderRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrderDetailResponse>>;
    apiOrderCreatePost(createOrderRequest: CreateOrderRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/Create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createOrderRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<OrderResponse>>;
    apiOrderGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<OrderResponse>>>;
    apiOrderGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<OrderResponse>>>;
    apiOrderGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderGetByIdIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrderDetailResponse>;
    apiOrderGetByIdIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrderDetailResponse>>;
    apiOrderGetByIdIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrderDetailResponse>>;
    apiOrderGetByIdIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/GetById/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderCancelIdPut(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrderResponse>;
    apiOrderCancelIdPut(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrderResponse>>;
    apiOrderCancelIdPut(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrderResponse>>;
    apiOrderCancelIdPut(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/Cancel/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('put', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderGetAllByAdminGet(status?: OrderStatus, page?: number | string, pageSize?: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedResultOfOrderResponse>;
    apiOrderGetAllByAdminGet(status?: OrderStatus, page?: number | string, pageSize?: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedResultOfOrderResponse>>;
    apiOrderGetAllByAdminGet(status?: OrderStatus, page?: number | string, pageSize?: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedResultOfOrderResponse>>;
    apiOrderGetAllByAdminGet(status?: OrderStatus, page?: number | string, pageSize?: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/GetAllByAdmin`;

        let params = new HttpParams();
        if (status != null) {
            params = HttpParamsBuilder.addToHttpParams(params, status, 'status');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderGetByIdByAdminIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrderDetailResponse>;
    apiOrderGetByIdByAdminIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrderDetailResponse>>;
    apiOrderGetByIdByAdminIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrderDetailResponse>>;
    apiOrderGetByIdByAdminIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/GetByIdByAdmin/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiOrderUpdateStatusByAdminPut(updateOrderStatusRequest: UpdateOrderStatusRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrderResponse>;
    apiOrderUpdateStatusByAdminPut(updateOrderStatusRequest: UpdateOrderStatusRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrderResponse>>;
    apiOrderUpdateStatusByAdminPut(updateOrderStatusRequest: UpdateOrderStatusRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrderResponse>>;
    apiOrderUpdateStatusByAdminPut(updateOrderStatusRequest: UpdateOrderStatusRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Order/UpdateStatusByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateOrderStatusRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
