// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Product controller
* Do not edit this file manually
*/
import {HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse} from '@angular/common/http';
import {inject, Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT} from '../tokens';
import {HttpParamsBuilder} from '../utils/http-params-builder';
import {CreateProductRequest, PagedResultOfProductResponse, ProductDetailResponse, ProductResponse, RequestOptions, UpdateProductRequest} from '../models';

@Injectable({ providedIn: "root" })
export class ProductService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiProductGet(categoryId?: string, search?: string, page?: number | string, pageSize?: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedResultOfProductResponse>;
    apiProductGet(categoryId?: string, search?: string, page?: number | string, pageSize?: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedResultOfProductResponse>>;
    apiProductGet(categoryId?: string, search?: string, page?: number | string, pageSize?: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedResultOfProductResponse>>;
    apiProductGet(categoryId?: string, search?: string, page?: number | string, pageSize?: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Product`;

        let params = new HttpParams();
        if (categoryId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, categoryId, 'categoryId');
        }
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiProductIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailResponse>;
    apiProductIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailResponse>>;
    apiProductIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailResponse>>;
    apiProductIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Product/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiProductCreateByAdminPost(createProductRequest: CreateProductRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductResponse>;
    apiProductCreateByAdminPost(createProductRequest: CreateProductRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductResponse>>;
    apiProductCreateByAdminPost(createProductRequest: CreateProductRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductResponse>>;
    apiProductCreateByAdminPost(createProductRequest: CreateProductRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Product/CreateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createProductRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiProductUpdateByAdminPut(updateProductRequest: UpdateProductRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductResponse>;
    apiProductUpdateByAdminPut(updateProductRequest: UpdateProductRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductResponse>>;
    apiProductUpdateByAdminPut(updateProductRequest: UpdateProductRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductResponse>>;
    apiProductUpdateByAdminPut(updateProductRequest: UpdateProductRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Product/UpdateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateProductRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiProductDeleteByAdminIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiProductDeleteByAdminIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiProductDeleteByAdminIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiProductDeleteByAdminIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Product/DeleteByAdmin/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
