// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for User controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { UpdateUserRequest, RequestOptions, UserResponse, CreateUserRequest } from "../models";

@Injectable({ providedIn: "root" })
export class UserService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiUserUpdatePut(updateUserRequest: UpdateUserRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserUpdatePut(updateUserRequest: UpdateUserRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserUpdatePut(updateUserRequest: UpdateUserRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserUpdatePut(updateUserRequest: UpdateUserRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/Update`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateUserRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserChangePasswordPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserChangePasswordPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserChangePasswordPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserChangePasswordPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/ChangePassword`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserMeGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserMeGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserMeGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserMeGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/Me`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserCreateByAdminPost(createUserRequest: CreateUserRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserCreateByAdminPost(createUserRequest: CreateUserRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserCreateByAdminPost(createUserRequest: CreateUserRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserCreateByAdminPost(createUserRequest: CreateUserRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/CreateByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createUserRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserUpdateByAdminIdPost(id: string, updateUserRequest: UpdateUserRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserUpdateByAdminIdPost(id: string, updateUserRequest: UpdateUserRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserUpdateByAdminIdPost(id: string, updateUserRequest: UpdateUserRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserUpdateByAdminIdPost(id: string, updateUserRequest: UpdateUserRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/UpdateByAdmin/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: updateUserRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserGetByIdByAdminIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserGetByIdByAdminIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserGetByIdByAdminIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserGetByIdByAdminIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/GetByIdByAdmin/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserGetByPhoneNumberByAdminPhoneNumberGet(phoneNumber: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserResponse>;
    apiUserGetByPhoneNumberByAdminPhoneNumberGet(phoneNumber: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserResponse>>;
    apiUserGetByPhoneNumberByAdminPhoneNumberGet(phoneNumber: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserResponse>>;
    apiUserGetByPhoneNumberByAdminPhoneNumberGet(phoneNumber: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/GetByPhoneNumberByAdmin/${phoneNumber}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    apiUserGetAllByAdminGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserGetAllByAdminGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserGetAllByAdminGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserGetAllByAdminGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/GetAllByAdmin`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
