// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import {HttpContext, HttpHeaders} from '@angular/common/http';
export interface AddCartItemRequest {
    productId: string;
    quantity: number | string;
}

export interface AddressResponse {
    id: string;
    title: string;
    addressLine1: string;
    addressLine2: string;
    phoneNumber: string;
    userId: string;
}

export interface CartItemResponse {
    productId: string;
    productName: string;
    imageUrl: string;
    originalPrice: number | string;
    unitPrice: number | string;
    quantity: number | string;
    lineTotal: number | string;
}

export interface CartResponse {
    id: string;
    items: Array<CartItemResponse>;
    totalAmount: number | string;
}

export interface CategoryResponse {
    id: string;
    name: string;
}

export interface CreateAddressRequest {
    title: string;
    addressLine1: string;
    addressLine2: string;
    phoneNumber: string;
    userId: string;
}

export interface CreateCategoryRequest {
    name: string;
}

export interface CreateOrderRequest {
    addressId: string;
    note: string | null;
}

export interface CreateProductRequest {
    name: string;
    price: number | string;
    isOnSale: boolean;
    salePrice: number | null | string | null | null;
    stockQuantity: number | string;
    isAvailable: boolean;
    categoryId: string;
    description?: string;
    imageUrl?: string;
}

export interface CreateUserRequest {
    firstName?: string;
    lastName?: string;
    email: string;
    phoneNumber: string;
    password: string;
}

export interface LoginRequest {
    phoneNumber: string;
    password: string;
}

export interface OrderDetailResponse {
    id: string;
    userId: string;
    status: string;
    totalAmount: number | string;
    note: string | null;
    createdAt: Date;
    updatedAt: Date;
    address: AddressResponse;
    items: Array<OrderItemResponse>;
}

export interface OrderItemResponse {
    productId: string;
    productName: string;
    unitPrice: number | string;
    quantity: number | string;
    lineTotal: number | string;
}

export interface OrderResponse {
    id: string;
    userId: string;
    status: string;
    totalAmount: number | string;
    note: string | null;
    createdAt: Date;
    updatedAt: Date;
}

export type OrderStatus = number;

export interface PagedResultOfOrderResponse {
    items: Array<OrderResponse>;
    totalCount: number | string;
    page: number | string;
    pageSize: number | string;
}

export interface PagedResultOfProductResponse {
    items: Array<ProductResponse>;
    totalCount: number | string;
    page: number | string;
    pageSize: number | string;
}

export interface ProductDetailResponse {
    id: string;
    name: string;
    description: string;
    price: number | string;
    isOnSale: boolean;
    salePrice: number | null | string | null | null;
    imageUrl: string;
    stockQuantity: number | string;
    isAvailable: boolean;
    categoryId: string;
    category: CategoryResponse;
    createdAt: Date;
    updatedAt: Date;
}

export interface ProductResponse {
    id: string;
    name: string;
    description: string;
    price: number | string;
    isOnSale: boolean;
    salePrice: number | null | string | null | null;
    imageUrl: string;
    stockQuantity: number | string;
    isAvailable: boolean;
    categoryId: string;
}

export interface RegisterRequest {
    phoneNumber: string;
    email: string;
    password: string;
}

export interface RegisterResponse {
    isSuccess?: boolean;
}

export interface UpdateAddressRequest {
    id: string;
    title: string;
    addressLine1: string;
    addressLine2: string;
    phoneNumber: string;
    userId: string;
}

export interface UpdateCartItemRequest {
    productId: string;
    quantity: number | string;
}

export interface UpdateCategoryRequest {
    id: string;
    name: string;
}

export interface UpdateOrderStatusRequest {
    orderId: string;
    status: string;
}

export interface UpdateProductRequest {
    id: string;
    name: string;
    price: number | string;
    isOnSale: boolean;
    salePrice: number | null | string | null | null;
    stockQuantity: number | string;
    isAvailable: boolean;
    categoryId: string;
    description?: string;
    imageUrl?: string;
}

export interface UpdateUserRequest {
    id: string;
    firstName?: string;
    lastName?: string;
    email: string;
    phoneNumber: string;
}

export interface UserResponse {
    id?: string;
    firstName?: string;
    lastName?: string;
    fullName?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
