// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated request parameter interfaces
* Do not edit this file manually
*/
import { CreateAddressRequest, UpdateAddressRequest, LoginRequest, RegisterRequest, AddCartItemRequest, UpdateCartItemRequest, CreateCategoryRequest, UpdateCategoryRequest, CreateOrderRequest, OrderStatus, UpdateOrderStatusRequest, CreateProductRequest, UpdateProductRequest, UpdateUserRequest, CreateUserRequest } from ".";

export interface ApiAddressCreatePostParams {
    createAddressRequest: CreateAddressRequest;
}

export interface ApiAddressUpdatePutParams {
    updateAddressRequest: UpdateAddressRequest;
}

export interface ApiAddressIdDeleteParams {
    id: string;
}

export interface ApiAddressGetAllByUserIdByAdminUserIdGetParams {
    userId: string;
}

export interface ApiAddressCreateByAdminPostParams {
    createAddressRequest: CreateAddressRequest;
}

export interface ApiAddressUpdateByAdminPutParams {
    updateAddressRequest: UpdateAddressRequest;
}

export interface ApiAuthLoginPostParams {
    loginRequest: LoginRequest;
}

export interface ApiAuthRegisterPostParams {
    registerRequest: RegisterRequest;
}

export interface ApiCartAddItemPostParams {
    addCartItemRequest: AddCartItemRequest;
}

export interface ApiCartUpdateItemPutParams {
    updateCartItemRequest: UpdateCartItemRequest;
}

export interface ApiCartRemoveItemProductIdDeleteParams {
    productId: string;
}

export interface ApiCategoryCreateByAdminPostParams {
    createCategoryRequest: CreateCategoryRequest;
}

export interface ApiCategoryUpdateByAdminPutParams {
    updateCategoryRequest: UpdateCategoryRequest;
}

export interface ApiCategoryDeleteByAdminIdDeleteParams {
    id: string;
}

export interface ApiOrderCreatePostParams {
    createOrderRequest: CreateOrderRequest;
}

export interface ApiOrderGetByIdIdGetParams {
    id: string;
}

export interface ApiOrderCancelIdPutParams {
    id: string;
}

export interface ApiOrderGetAllByAdminGetParams {
    status?: OrderStatus;
    page?: number | string;
    pageSize?: number | string;
}

export interface ApiOrderGetByIdByAdminIdGetParams {
    id: string;
}

export interface ApiOrderUpdateStatusByAdminPutParams {
    updateOrderStatusRequest: UpdateOrderStatusRequest;
}

export interface ApiProductGetParams {
    categoryId?: string;
    search?: string;
    page?: number | string;
    pageSize?: number | string;
}

export interface ApiProductIdGetParams {
    id: string;
}

export interface ApiProductCreateByAdminPostParams {
    createProductRequest: CreateProductRequest;
}

export interface ApiProductUpdateByAdminPutParams {
    updateProductRequest: UpdateProductRequest;
}

export interface ApiProductDeleteByAdminIdDeleteParams {
    id: string;
}

export interface ApiUserUpdatePutParams {
    updateUserRequest: UpdateUserRequest;
}

export interface ApiUserCreateByAdminPostParams {
    createUserRequest: CreateUserRequest;
}

export interface ApiUserUpdateByAdminIdPostParams {
    id: string;
    updateUserRequest: UpdateUserRequest;
}

export interface ApiUserGetByIdByAdminIdGetParams {
    id: string;
}

export interface ApiUserGetByPhoneNumberByAdminPhoneNumberGetParams {
    phoneNumber: string;
}
